Create Skill class (idk how this works)
Adonis-Self-Improvement/ASI-DiscordBot pull request #22
Opened 2022-03-23 22:06 UTC by seanjhardy

Create ~skill test command
Refactor the code to conform to ESLint
Add assets file and test assets
Setup environment for deployment

**Please describe the changes this PR makes and why it should be merged, as well as any and all proof of successful tests:**

**Semantic versioning classification:**

- [ ] This PR changes the framework's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to README, etc.

2022-03-23 22:12 UTC, swatarianess approved these changes
Good job! Looks neet.

2022-03-23 23:10 UTC, swatarianess requested changes
Added 2 comments :)

2022-03-23 23:10 UTC, swatarianess commented on commands/conf.js
> +FOR GUILD bSETTINGS SEE set.js !
Fixing mispelling.

2022-03-23 23:10 UTC, swatarianess commented on config.js
> +    "prefix": "s/",
why `s/` instead of `~` ?

2022-03-24 03:39 UTC, iJynx commented on config.js
> +    "prefix": "s/",
We have ~ for jeffrey bot and every second person doesn't know the difference betwen ~ and -

2022-03-24 03:41 UTC, iJynx approved these changes
Looks alright, i'll do the rest later.

2022-03-24 15:13 UTC, swatarianess approved these changes

2022-03-24 15:13 UTC, merged