Swipeable interface
Adonis-Self-Improvement/ASI-DiscordBot pull request #41
Opened 2022-03-27 20:37 UTC by seanjhardy

**Please describe the changes this PR makes and why it should be merged, as well as any and all proof of successful tests:**

**Semantic versioning classification:**

- [x] This PR changes the framework's interface (methods or parameters added)
  - [x] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to README, etc.

2022-03-27 20:42 UTC, seanjhardy commented
Why does it keep committing old commits 🤔

2022-03-27 21:02 UTC, swatarianess commented on commands/eval.js
> +  if (text && text.constructor.name === "Promise")
Why we doing a `===` comparsion instead of a `==` comparison. The 3 equals also checks the data types are the same, don't think that is necessary?

2022-03-27 21:10 UTC, swatarianess requested changes
Tiny change, I left with a comment in the `commands/eval.js` file. Other than that, looks good.

2022-03-27 21:19 UTC, Alenygam commented
lgtm

2022-03-27 21:22 UTC, Alenygam approved these changes
Quickly went through the changes and lgtm.

2022-03-28 07:20 UTC, swatarianess commented
> Why does it keep committing old commits 🤔

ahh, try this? Not sure why it pulls up some of the git history.

![image](https://user-images.githubusercontent.com/1682734/160342377-c9565667-c2c0-4d82-b673-f9ccdc5d8163.png)

2022-03-28 08:06 UTC, swatarianess submitted a review, later dismissed

2022-03-28 10:09 UTC, Alenygam submitted a review, later dismissed
still lgtm

2022-03-28 12:32 UTC, swatarianess approved these changes

2022-03-28 13:23 UTC, vlyr approved these changes
Yes please.

2022-03-28 13:30 UTC, merged